spring.application.name=student-api

# Configuracion del Puerto del Servidor
server.port=8080
# Configuracion de la Base de Datos H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Configuracion de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Habilitar Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Configuracion adicional
spring.jpa.defer-datasource-initialization=true
